### ISSUE TITLE
Redirecting after login

### ISSUE THREAD

**Issue by shan916** [auth0/angular-jwt#147]
After the redirect to the login page has occurred, is there a way to redirect to the original page after login? I know I can save the state that the user was trying to access into $rootScope on the $stateChangeStart event. But I think being able to have that feature in angular-jwt would be great if possible.

**Comment by konstpeppas** [comment]
Yeah this would be a nice feature. This would be possible if the state was injected in config.unauthenticatedRedirector. It is possible to inject $state and take $state.current. But this works only when the redirector is called by the http interceptor, not when accessing a protected state because the state has not changed yet, so the $state.current gives the previous state.
