### ISSUE TITLE
Use jwtInterceptor to send the token as a request param?

### ISSUE THREAD

**Issue by mattblang** [auth0/angular-jwt#26]
I am using WebSockets and, for reasons that have to do with my back-end framework, can only use request params to send the token.  Is there a way to create a jwtInterceptor that will accomplish this, or is sending via header the only possibility?

**Comment by mgonto** [comment]
Using this library, right now it's only possible to send it in the header.

However, you could easily implement it so that it uses the request params. You can change [this line](https://github.com/auth0/angular-jwt/blob/master/src/angularJwt/services/interceptor.js#L31) to use `request.params` instead of `request.headers` and that'd be it.

We'd be open to a PR if you want to make the header / param an option to the library :).

Cheers!

**Comment by mattblang** [comment]
@mgonto This worked great!  Thank you so much.

**Comment by mgonto** [comment]
Hey,

Would you care to send a PR so that we can make it configurable where to send the JWT, either header or request params?

Thanks!
