### ISSUE TITLE
Refreshed JWT not available

### ISSUE THREAD

**Issue by pdoreau** [auth0/angular-jwt#57]
Hi. Is this case possible :
- JWT is refreshed as [explained](https://github.com/auth0/angular-jwt#using-promises-on-the-tokengetter-refresh-token-example)
- However, API takes time to send the refreshed token
- Due to async behavior and promise, another API call is made on a business resource but refreshed token is not yet available. Authorization header is defined with the expired token.
- A not authorized response is returned because used token is expired
- Refreshed token is finally returned ... too late

How to handle such a case ? Is there something to change in the [example](https://github.com/auth0/angular-jwt#using-promises-on-the-tokengetter-refresh-token-example) or in the bundle source code ?

**Comment by justechn** [comment]
The best thing you can do is refresh your tokens before the expire. That way you will not run into this problem. If you have a 15 min expire, refresh your token at 13 or 14 min.

**Comment by petejohanson** [comment]
Thinking about this for my own scenario, I wonder if something like the following would work:

```javascript
var refreshPromise;
jwtInterceptorProvider.tokenGetter = function(config) {
  if (refreshPromise) {
    return refreshPromise;
  }

  var token = window.localStorage.getItem('access_token');
  if (jwtHelper.isExpired(token)) {
    refreshPromise = refreshToken();
    return refreshPromise.then(r => {
      refreshPromise = null;
      return r;
    }, err => {
      refreshPromise = null;
      throw err;
    });
  }

  return token;
}
```

Re-using the promise created for refreshing the token *should* let your subsequent requests "queue up" until the token is refreshed, then all the awaiting requests would get the new token.

Caveats: I'm planning on trying this approach, but I'm not sure if the internals of angular-jwt will somehow conflict w/ this idea.

Authors: Thoughts?

**Comment by petejohanson** [comment]
I've just implemented something as I described in my previous comment, and it seems to work as expected. Multiple "pending" requests get queue'd up if you re-use the promise representing the in-progress refresh, and then clear the saved pending request after the refresh completes.

**Comment by ajoslin103** [comment]
that looks good, I've been running into the async problem (I've lots of calls all using the jwt) -- I'd be interested in your working solution if you cared to post it.

I'm trying to implement 1-token, 1-call (where the token is refreshed on the server for every call) and I need a blocking solution like this so that every requestor gets the new token

I've been fighting $resource interceptors (which are not covered by the supplied $http  interceptor) -- I've almost got it (I hope.)

**Comment by GabrielGil** [comment]
@petejohanson's solution seems nice to me and works just fine. 💃

**Comment by ajoslin103** [comment]
@petejohanson -- could you share your final code?

**Comment by petejohanson** [comment]
Unfortunately my final solution is more complicated because of other requirements, and is for work so I can't share here. However, the essence of the working version I implemented is exactly like the sample I posted previously.

You would just need to fill in the actual implementation of your `refreshToken` function to return a proper promise.

**Comment by GabrielGil** [comment]
Exactly, well, I just got you idea. My implementation differs as well a little. But the essence of your snippet is the essence of the solution. Thank you again!

**Comment by ajoslin103** [comment]
Mine didn't work so well -- I'll have to go back and compare it to your direction -- thanks anyway

**Comment by petejohanson** [comment]
@ajoslin103 if you want to create a gist of your version and link it here, we can see if we can offer some advise?

**Comment by GabrielGil** [comment]
@ajoslin103 I can't really share my final code, but this is a modified version of the example shown on the README.md of the repo, and the solution suggested by @petejohanson 

This example stamps subsequent calls after a token expired, and resumes then to be sent with the new token after the promise has been resolved. (Thus only one call to the refresh endpoint is performed).

``` javascript
angular.module('app', ['angular-jwt'])
.config(function Config($httpProvider, jwtInterceptorProvider) {
  var refreshPromise;
  jwtInterceptorProvider.tokenGetter = ['jwtHelper', '$http', function(jwtHelper, $http) {
    if (refreshPromise) {
      return refreshPromise;
    }
    var idToken = localStorage.getItem('id_token');
    var refreshToken = localStorage.getItem('refresh_token');

    if (jwtHelper.isTokenExpired(idToken)) {
      // This is a promise of a JWT id_token
      refreshPromise = $http({
        url: '/delegation',
        // This makes it so that this request doesn't send the JWT
        skipAuthorization: true,
        method: 'POST',
        data: { 
            grant_type: 'refresh_token',
            refresh_token: refreshToken 
        }
      })

    return refreshPromise.then(function(response) {
        var id_token = response.data.id_token;
        localStorage.setItem('id_token', id_token);
        refreshPromise = null
        return id_token;
      });
    } else {
      return idToken;
    }
  }];
  $httpProvider.interceptors.push('jwtInterceptor');
})
```

Note the difference with the example on the main page that we store the $http promise in the variable that is gonna be checked on subsequent tokenGetter calls

I really hope this helps ;)

**Comment by ajoslin103** [comment]
that project finished with an acceptance on the login JWT expiring in 2hrs, rather than auto-renewing

and I’m not using Angular anymore, I’ve moved on to Aurelia

I hope to use JWT again in soon in which case I’ll have another go at starting from your snippet

thanks
al;

**Comment by ajoslin103** [comment]
thanks to you both -- I know I'll hit this issue again soon

**Comment by GabrielGil** [comment]
:sweat_smile:

**Comment by petejohanson** [comment]
I think @GabrielGil's updates to the README.md should be integrated there, this seems like a common enough need.

**Comment by GabrielGil** [comment]
I've created a pull request after your suggestions guys (#77) :D

**Comment by zbjornson** [comment]
Appreciate the examples and discussion here!

I had to modify @GabrielGil's approach slightly to store the new promise created by `then`, otherwise jwtInterceptor made the http request before the refresh promise had fully resolved (the network request has the header "Authorization: [object Object]")

```js
angular.module('app', ['angular-jwt'])
.config(function Config($httpProvider, jwtInterceptorProvider) {
    var refreshPromise;
    jwtInterceptorProvider.tokenGetter = ['jwtHelper', '$http', function(jwtHelper, $http) {
        if (refreshPromise) {
            return refreshPromise;
        }
        var idToken = localStorage.getItem('id_token');
        if (jwtHelper.isTokenExpired(idToken)) {
            var refreshToken = localStorage.getItem('refresh_token');
            // This is a promise of a JWT id_token
            refreshPromise = $http({
                url: '/delegation',
                // This makes it so that this request doesn't send the JWT
                skipAuthorization: true,
                method: 'POST',
                data: { 
                    grant_type: 'refresh_token',
                    refresh_token: refreshToken 
                }
            }).then(function(response) {
                var id_token = response.data.id_token;
                localStorage.setItem('id_token', id_token);
                refreshPromise = null
                return id_token;
            });
            return refreshPromise
        } else {
            return idToken;
        }
    }];
    $httpProvider.interceptors.push('jwtInterceptor');
})
```

**Comment by GabrielGil** [comment]
Hey @zbjornson!!

You are definitely right, and actually I had modify like so in my code, but forgot to modify the example. I am fixing my previous comment and the PR I got open to include this in the documentation.

Thank you!

**Comment by dzuluaga** [comment]
Thanks @petejohanson. Your solution worked for me. My suggestion is to update all examples with the approach described here. Otherwise, you'll get `429 too many requests`. Here are two sources, which require to be updated as they have missing the outer refreshPromise:

https://github.com/auth0/angular-jwt#using-promises-on-the-tokengetter-refresh-token-example
https://auth0.com/blog/2014/10/01/handling-jwts-on-angular-is-finally-easier/

Cheers!

**Comment by pabloleone** [comment]
I realized that the backend should return a 200 response code even if token can't be refreshed because the JWT package will loop forever as it isn't expecting a failing request (second parameter of `then` method). We're using the JWT package for Laravel and it's implementation returns an exception (401) when the token is completely expired and ready to blacklist. Which philosophy is the right one?
