### ISSUE TITLE
can't decode token from jsonwebtoken on node

### ISSUE THREAD

**Issue by avatarr** [auth0/angular-jwt#65]
Hello , a few day I use angular-jwt to decode token from backend (nodejs) ,When I decede is working ok , but today angular-jwt can't decode I get result as "Object {_bsontype: "ObjectID", id: "VuÔy±Õ#", iat: 1452054188}" , So result must have object that I get from backend like a few day, How do I fix this issues 

my token is a "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYnNvbnR5cGUiOiJPYmplY3RJRCIsImlkIjoiVsKLdcOUecKWwrHDlVx1MDAxOMKSI8KBIiwiaWF0IjoxNDUyMDU0MTg4fQ.BWa6oha9nkx4WPxC5l_K-tya65aovAEgXY0tVvAuaEg"

ps. I have us mean.io to build my application
Thank.

**Comment by Shimmi** [comment]
Hi @avatarr,
Seems the issue is on your backend. The library decodes the token correctly. The token itself really holds those data. Just try to paste it on http://jwt.io website to check the output.

It contains those payload data:
`{
  "_bsontype": "ObjectID",
  "id": "VuÔy±Õ\u0018#",
  "iat": 1452054188
}`
